// AUTO-GENERATED by gen_wb_aes.py -- DO NOT EDIT
#pragma once
#include <cstdint>
#include <cstring>
#include "wb_tables.h"

#ifdef __x86_64__
#define WB_OVERLAP_0() do { __asm__ volatile("movl %%esp, %%eax\n\tleal 1(%%eax), %%ecx\n\timull %%ecx, %%eax\n\ttestl $1, %%eax\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0x48, 0xb9\n\t" ".byte 0x04, 0xc5, 0x65, 0xd8, 0x5e, 0x8a, 0xa1\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory"); } while(0)
#define WB_OVERLAP_1() do { __asm__ volatile("movl %%esp, %%eax\n\timull $4, %%eax, %%ecx\n\taddl %%eax, %%eax\n\tsubl %%eax, %%ecx\n\tsubl %%eax, %%ecx\n\ttestl %%ecx, %%ecx\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0x48, 0x81, 0xf0\n\t" ".byte 0xea, 0x97, 0xc7\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory"); } while(0)
#define WB_OVERLAP_2() do { __asm__ volatile("movl %%esp, %%eax\n\timull $3, %%eax, %%ecx\n\tleal (%%eax,%%eax,2), %%eax\n\txorl %%ecx, %%eax\n\ttestl %%eax, %%eax\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0x68\n\t" ".byte 0x34, 0xe5, 0x16\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory"); } while(0)
#define WB_OVERLAP_3() do { __asm__ volatile("movl %%esp, %%eax\n\tmovl %%eax, %%ecx\n\troll $11, %%ecx\n\trorl $11, %%ecx\n\txorl %%eax, %%ecx\n\ttestl %%ecx, %%ecx\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0x48, 0xbb\n\t" ".byte 0x87, 0xc2, 0xf3, 0xf0, 0x4d, 0x5b, 0xdc\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory"); } while(0)
#define WB_OVERLAP_4() do { __asm__ volatile("movl %%esp, %%eax\n\tleal (%%eax,%%eax), %%ecx\n\tsubl %%eax, %%ecx\n\tsubl %%eax, %%ecx\n\ttestl %%ecx, %%ecx\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0x48, 0x81, 0xf2\n\t" ".byte 0x0b, 0xf4, 0x86\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory"); } while(0)
#define WB_OVERLAP_5() do { __asm__ volatile("movl %%esp, %%eax\n\tleal (%%eax,%%eax), %%ecx\n\timull $2, %%eax, %%eax\n\txorl %%ecx, %%eax\n\ttestl %%eax, %%eax\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0xb8\n\t" ".byte 0xe6, 0x46, 0x82\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory"); } while(0)
#define WB_OVERLAP_6() do { __asm__ volatile("movl %%esp, %%eax\n\tmovl $1, %%ecx\n\tmulq %%rcx\n\ttestl %%edx, %%edx\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0x48, 0xbd\n\t" ".byte 0x3d, 0xcb, 0xb1, 0x03, 0x16, 0x72, 0x42\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory", "edx"); } while(0)
#define WB_OVERLAP_7() do { __asm__ volatile("movl %%esp, %%eax\n\tmovl %%ebp, %%ecx\n\txorl %%ecx, %%eax\n\txorl %%ecx, %%eax\n\txorl %%esp, %%eax\n\ttestl %%eax, %%eax\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0x48, 0x81, 0xf5\n\t" ".byte 0xdc, 0x0a, 0xe5\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory"); } while(0)
#define WB_OVERLAP_8() do { __asm__ volatile("movl %%esp, %%eax\n\tmovl %%ebp, %%ecx\n\torl  %%ecx, %%eax\n\tandl %%esp, %%ecx\n\taddl %%ecx, %%eax\n\timull $1, %%esp, %%ecx\n\tsubl %%ecx, %%eax\n\tsubl %%ebp, %%eax\n\ttestl %%eax, %%eax\n\t" "jnz 2f\n\t" "jmp 1f\n\t" "2:\n\t" ".byte 0xba\n\t" ".byte 0x3b, 0xf6, 0x5a\n\t" "1:\n\t" ::: "eax", "ecx", "cc", "memory"); } while(0)
#else
#define WB_OVERLAP_0() do {} while(0)
#define WB_OVERLAP_1() do {} while(0)
#define WB_OVERLAP_2() do {} while(0)
#define WB_OVERLAP_3() do {} while(0)
#define WB_OVERLAP_4() do {} while(0)
#define WB_OVERLAP_5() do {} while(0)
#define WB_OVERLAP_6() do {} while(0)
#define WB_OVERLAP_7() do {} while(0)
#define WB_OVERLAP_8() do {} while(0)
#endif

static __attribute__((noinline)) void wb_aes_encrypt(const uint8_t in[16], uint8_t out[16]) {
    uint8_t s0, s1, s2, s3, s4, s5, s6, s7,
            s8, s9, s10, s11, s12, s13, s14, s15;
    uint32_t W0, W1, W2, W3;
    uint8_t ab0, ab1, ab2, ab3, ab4, ab5, ab6, ab7;
    uint8_t cd0, cd1, cd2, cd3, cd4, cd5, cd6, cd7;
    uint8_t fn0, fn1, fn2, fn3, fn4, fn5, fn6, fn7;

    s0 = in[0];
    s1 = in[1];
    s2 = in[2];
    s3 = in[3];
    s4 = in[4];
    s5 = in[5];
    s6 = in[6];
    s7 = in[7];
    s8 = in[8];
    s9 = in[9];
    s10 = in[10];
    s11 = in[11];
    s12 = in[12];
    s13 = in[13];
    s14 = in[14];
    s15 = in[15];

    // ---- Round 0 ----
    // Round 0, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[0][0][s0];
    W1 = tyi_tab[0][5][s5];
    W2 = tyi_tab[0][10][s10];
    W3 = tyi_tab[0][15][s15];
    WB_OVERLAP_0();
    WB_OVERLAP_0();
    ab0 = xor_tab[0][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[0][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[0][0][2][0][ab0][cd0];
    WB_OVERLAP_0();
    ab1 = xor_tab[0][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[0][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[0][0][2][1][ab1][cd1];
    WB_OVERLAP_0();
    ab2 = xor_tab[0][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[0][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[0][0][2][2][ab2][cd2];
    WB_OVERLAP_0();
    ab3 = xor_tab[0][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[0][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[0][0][2][3][ab3][cd3];
    WB_OVERLAP_0();
    ab4 = xor_tab[0][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[0][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[0][0][2][4][ab4][cd4];
    WB_OVERLAP_0();
    ab5 = xor_tab[0][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[0][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[0][0][2][5][ab5][cd5];
    WB_OVERLAP_0();
    ab6 = xor_tab[0][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[0][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[0][0][2][6][ab6][cd6];
    WB_OVERLAP_0();
    ab7 = xor_tab[0][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[0][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[0][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n0_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n0_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n0_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n0_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 0, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[0][4][s4];
    W1 = tyi_tab[0][9][s9];
    W2 = tyi_tab[0][14][s14];
    W3 = tyi_tab[0][3][s3];
    WB_OVERLAP_0();
    WB_OVERLAP_0();
    ab0 = xor_tab[0][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[0][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[0][1][2][0][ab0][cd0];
    WB_OVERLAP_0();
    ab1 = xor_tab[0][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[0][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[0][1][2][1][ab1][cd1];
    WB_OVERLAP_0();
    ab2 = xor_tab[0][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[0][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[0][1][2][2][ab2][cd2];
    WB_OVERLAP_0();
    ab3 = xor_tab[0][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[0][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[0][1][2][3][ab3][cd3];
    WB_OVERLAP_0();
    ab4 = xor_tab[0][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[0][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[0][1][2][4][ab4][cd4];
    WB_OVERLAP_0();
    ab5 = xor_tab[0][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[0][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[0][1][2][5][ab5][cd5];
    WB_OVERLAP_0();
    ab6 = xor_tab[0][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[0][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[0][1][2][6][ab6][cd6];
    WB_OVERLAP_0();
    ab7 = xor_tab[0][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[0][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[0][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n0_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n0_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n0_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n0_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 0, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[0][8][s8];
    W1 = tyi_tab[0][13][s13];
    W2 = tyi_tab[0][2][s2];
    W3 = tyi_tab[0][7][s7];
    WB_OVERLAP_0();
    WB_OVERLAP_0();
    ab0 = xor_tab[0][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[0][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[0][2][2][0][ab0][cd0];
    WB_OVERLAP_0();
    ab1 = xor_tab[0][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[0][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[0][2][2][1][ab1][cd1];
    WB_OVERLAP_0();
    ab2 = xor_tab[0][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[0][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[0][2][2][2][ab2][cd2];
    WB_OVERLAP_0();
    ab3 = xor_tab[0][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[0][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[0][2][2][3][ab3][cd3];
    WB_OVERLAP_0();
    ab4 = xor_tab[0][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[0][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[0][2][2][4][ab4][cd4];
    WB_OVERLAP_0();
    ab5 = xor_tab[0][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[0][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[0][2][2][5][ab5][cd5];
    WB_OVERLAP_0();
    ab6 = xor_tab[0][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[0][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[0][2][2][6][ab6][cd6];
    WB_OVERLAP_0();
    ab7 = xor_tab[0][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[0][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[0][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n0_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n0_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n0_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n0_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 0, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[0][12][s12];
    W1 = tyi_tab[0][1][s1];
    W2 = tyi_tab[0][6][s6];
    W3 = tyi_tab[0][11][s11];
    WB_OVERLAP_0();
    WB_OVERLAP_0();
    ab0 = xor_tab[0][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[0][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[0][3][2][0][ab0][cd0];
    WB_OVERLAP_0();
    ab1 = xor_tab[0][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[0][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[0][3][2][1][ab1][cd1];
    WB_OVERLAP_0();
    ab2 = xor_tab[0][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[0][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[0][3][2][2][ab2][cd2];
    WB_OVERLAP_0();
    ab3 = xor_tab[0][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[0][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[0][3][2][3][ab3][cd3];
    WB_OVERLAP_0();
    ab4 = xor_tab[0][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[0][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[0][3][2][4][ab4][cd4];
    WB_OVERLAP_0();
    ab5 = xor_tab[0][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[0][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[0][3][2][5][ab5][cd5];
    WB_OVERLAP_0();
    ab6 = xor_tab[0][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[0][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[0][3][2][6][ab6][cd6];
    WB_OVERLAP_0();
    ab7 = xor_tab[0][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[0][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[0][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n0_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n0_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n0_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n0_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 1 ----
    // Round 1, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[1][0][n0_0];
    W1 = tyi_tab[1][5][n0_5];
    W2 = tyi_tab[1][10][n0_10];
    W3 = tyi_tab[1][15][n0_15];
    WB_OVERLAP_1();
    WB_OVERLAP_1();
    ab0 = xor_tab[1][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[1][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[1][0][2][0][ab0][cd0];
    WB_OVERLAP_1();
    ab1 = xor_tab[1][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[1][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[1][0][2][1][ab1][cd1];
    WB_OVERLAP_1();
    ab2 = xor_tab[1][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[1][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[1][0][2][2][ab2][cd2];
    WB_OVERLAP_1();
    ab3 = xor_tab[1][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[1][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[1][0][2][3][ab3][cd3];
    WB_OVERLAP_1();
    ab4 = xor_tab[1][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[1][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[1][0][2][4][ab4][cd4];
    WB_OVERLAP_1();
    ab5 = xor_tab[1][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[1][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[1][0][2][5][ab5][cd5];
    WB_OVERLAP_1();
    ab6 = xor_tab[1][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[1][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[1][0][2][6][ab6][cd6];
    WB_OVERLAP_1();
    ab7 = xor_tab[1][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[1][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[1][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n1_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n1_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n1_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n1_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 1, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[1][4][n0_4];
    W1 = tyi_tab[1][9][n0_9];
    W2 = tyi_tab[1][14][n0_14];
    W3 = tyi_tab[1][3][n0_3];
    WB_OVERLAP_1();
    WB_OVERLAP_1();
    ab0 = xor_tab[1][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[1][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[1][1][2][0][ab0][cd0];
    WB_OVERLAP_1();
    ab1 = xor_tab[1][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[1][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[1][1][2][1][ab1][cd1];
    WB_OVERLAP_1();
    ab2 = xor_tab[1][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[1][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[1][1][2][2][ab2][cd2];
    WB_OVERLAP_1();
    ab3 = xor_tab[1][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[1][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[1][1][2][3][ab3][cd3];
    WB_OVERLAP_1();
    ab4 = xor_tab[1][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[1][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[1][1][2][4][ab4][cd4];
    WB_OVERLAP_1();
    ab5 = xor_tab[1][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[1][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[1][1][2][5][ab5][cd5];
    WB_OVERLAP_1();
    ab6 = xor_tab[1][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[1][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[1][1][2][6][ab6][cd6];
    WB_OVERLAP_1();
    ab7 = xor_tab[1][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[1][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[1][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n1_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n1_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n1_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n1_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 1, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[1][8][n0_8];
    W1 = tyi_tab[1][13][n0_13];
    W2 = tyi_tab[1][2][n0_2];
    W3 = tyi_tab[1][7][n0_7];
    WB_OVERLAP_1();
    WB_OVERLAP_1();
    ab0 = xor_tab[1][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[1][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[1][2][2][0][ab0][cd0];
    WB_OVERLAP_1();
    ab1 = xor_tab[1][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[1][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[1][2][2][1][ab1][cd1];
    WB_OVERLAP_1();
    ab2 = xor_tab[1][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[1][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[1][2][2][2][ab2][cd2];
    WB_OVERLAP_1();
    ab3 = xor_tab[1][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[1][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[1][2][2][3][ab3][cd3];
    WB_OVERLAP_1();
    ab4 = xor_tab[1][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[1][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[1][2][2][4][ab4][cd4];
    WB_OVERLAP_1();
    ab5 = xor_tab[1][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[1][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[1][2][2][5][ab5][cd5];
    WB_OVERLAP_1();
    ab6 = xor_tab[1][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[1][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[1][2][2][6][ab6][cd6];
    WB_OVERLAP_1();
    ab7 = xor_tab[1][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[1][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[1][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n1_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n1_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n1_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n1_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 1, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[1][12][n0_12];
    W1 = tyi_tab[1][1][n0_1];
    W2 = tyi_tab[1][6][n0_6];
    W3 = tyi_tab[1][11][n0_11];
    WB_OVERLAP_1();
    WB_OVERLAP_1();
    ab0 = xor_tab[1][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[1][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[1][3][2][0][ab0][cd0];
    WB_OVERLAP_1();
    ab1 = xor_tab[1][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[1][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[1][3][2][1][ab1][cd1];
    WB_OVERLAP_1();
    ab2 = xor_tab[1][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[1][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[1][3][2][2][ab2][cd2];
    WB_OVERLAP_1();
    ab3 = xor_tab[1][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[1][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[1][3][2][3][ab3][cd3];
    WB_OVERLAP_1();
    ab4 = xor_tab[1][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[1][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[1][3][2][4][ab4][cd4];
    WB_OVERLAP_1();
    ab5 = xor_tab[1][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[1][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[1][3][2][5][ab5][cd5];
    WB_OVERLAP_1();
    ab6 = xor_tab[1][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[1][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[1][3][2][6][ab6][cd6];
    WB_OVERLAP_1();
    ab7 = xor_tab[1][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[1][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[1][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n1_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n1_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n1_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n1_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 2 ----
    // Round 2, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[2][0][n1_0];
    W1 = tyi_tab[2][5][n1_5];
    W2 = tyi_tab[2][10][n1_10];
    W3 = tyi_tab[2][15][n1_15];
    WB_OVERLAP_2();
    WB_OVERLAP_2();
    ab0 = xor_tab[2][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[2][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[2][0][2][0][ab0][cd0];
    WB_OVERLAP_2();
    ab1 = xor_tab[2][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[2][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[2][0][2][1][ab1][cd1];
    WB_OVERLAP_2();
    ab2 = xor_tab[2][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[2][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[2][0][2][2][ab2][cd2];
    WB_OVERLAP_2();
    ab3 = xor_tab[2][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[2][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[2][0][2][3][ab3][cd3];
    WB_OVERLAP_2();
    ab4 = xor_tab[2][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[2][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[2][0][2][4][ab4][cd4];
    WB_OVERLAP_2();
    ab5 = xor_tab[2][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[2][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[2][0][2][5][ab5][cd5];
    WB_OVERLAP_2();
    ab6 = xor_tab[2][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[2][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[2][0][2][6][ab6][cd6];
    WB_OVERLAP_2();
    ab7 = xor_tab[2][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[2][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[2][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n2_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n2_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n2_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n2_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 2, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[2][4][n1_4];
    W1 = tyi_tab[2][9][n1_9];
    W2 = tyi_tab[2][14][n1_14];
    W3 = tyi_tab[2][3][n1_3];
    WB_OVERLAP_2();
    WB_OVERLAP_2();
    ab0 = xor_tab[2][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[2][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[2][1][2][0][ab0][cd0];
    WB_OVERLAP_2();
    ab1 = xor_tab[2][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[2][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[2][1][2][1][ab1][cd1];
    WB_OVERLAP_2();
    ab2 = xor_tab[2][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[2][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[2][1][2][2][ab2][cd2];
    WB_OVERLAP_2();
    ab3 = xor_tab[2][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[2][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[2][1][2][3][ab3][cd3];
    WB_OVERLAP_2();
    ab4 = xor_tab[2][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[2][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[2][1][2][4][ab4][cd4];
    WB_OVERLAP_2();
    ab5 = xor_tab[2][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[2][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[2][1][2][5][ab5][cd5];
    WB_OVERLAP_2();
    ab6 = xor_tab[2][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[2][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[2][1][2][6][ab6][cd6];
    WB_OVERLAP_2();
    ab7 = xor_tab[2][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[2][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[2][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n2_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n2_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n2_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n2_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 2, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[2][8][n1_8];
    W1 = tyi_tab[2][13][n1_13];
    W2 = tyi_tab[2][2][n1_2];
    W3 = tyi_tab[2][7][n1_7];
    WB_OVERLAP_2();
    WB_OVERLAP_2();
    ab0 = xor_tab[2][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[2][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[2][2][2][0][ab0][cd0];
    WB_OVERLAP_2();
    ab1 = xor_tab[2][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[2][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[2][2][2][1][ab1][cd1];
    WB_OVERLAP_2();
    ab2 = xor_tab[2][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[2][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[2][2][2][2][ab2][cd2];
    WB_OVERLAP_2();
    ab3 = xor_tab[2][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[2][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[2][2][2][3][ab3][cd3];
    WB_OVERLAP_2();
    ab4 = xor_tab[2][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[2][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[2][2][2][4][ab4][cd4];
    WB_OVERLAP_2();
    ab5 = xor_tab[2][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[2][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[2][2][2][5][ab5][cd5];
    WB_OVERLAP_2();
    ab6 = xor_tab[2][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[2][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[2][2][2][6][ab6][cd6];
    WB_OVERLAP_2();
    ab7 = xor_tab[2][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[2][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[2][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n2_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n2_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n2_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n2_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 2, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[2][12][n1_12];
    W1 = tyi_tab[2][1][n1_1];
    W2 = tyi_tab[2][6][n1_6];
    W3 = tyi_tab[2][11][n1_11];
    WB_OVERLAP_2();
    WB_OVERLAP_2();
    ab0 = xor_tab[2][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[2][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[2][3][2][0][ab0][cd0];
    WB_OVERLAP_2();
    ab1 = xor_tab[2][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[2][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[2][3][2][1][ab1][cd1];
    WB_OVERLAP_2();
    ab2 = xor_tab[2][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[2][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[2][3][2][2][ab2][cd2];
    WB_OVERLAP_2();
    ab3 = xor_tab[2][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[2][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[2][3][2][3][ab3][cd3];
    WB_OVERLAP_2();
    ab4 = xor_tab[2][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[2][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[2][3][2][4][ab4][cd4];
    WB_OVERLAP_2();
    ab5 = xor_tab[2][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[2][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[2][3][2][5][ab5][cd5];
    WB_OVERLAP_2();
    ab6 = xor_tab[2][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[2][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[2][3][2][6][ab6][cd6];
    WB_OVERLAP_2();
    ab7 = xor_tab[2][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[2][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[2][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n2_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n2_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n2_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n2_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 3 ----
    // Round 3, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[3][0][n2_0];
    W1 = tyi_tab[3][5][n2_5];
    W2 = tyi_tab[3][10][n2_10];
    W3 = tyi_tab[3][15][n2_15];
    WB_OVERLAP_3();
    WB_OVERLAP_3();
    ab0 = xor_tab[3][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[3][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[3][0][2][0][ab0][cd0];
    WB_OVERLAP_3();
    ab1 = xor_tab[3][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[3][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[3][0][2][1][ab1][cd1];
    WB_OVERLAP_3();
    ab2 = xor_tab[3][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[3][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[3][0][2][2][ab2][cd2];
    WB_OVERLAP_3();
    ab3 = xor_tab[3][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[3][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[3][0][2][3][ab3][cd3];
    WB_OVERLAP_3();
    ab4 = xor_tab[3][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[3][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[3][0][2][4][ab4][cd4];
    WB_OVERLAP_3();
    ab5 = xor_tab[3][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[3][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[3][0][2][5][ab5][cd5];
    WB_OVERLAP_3();
    ab6 = xor_tab[3][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[3][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[3][0][2][6][ab6][cd6];
    WB_OVERLAP_3();
    ab7 = xor_tab[3][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[3][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[3][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n3_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n3_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n3_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n3_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 3, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[3][4][n2_4];
    W1 = tyi_tab[3][9][n2_9];
    W2 = tyi_tab[3][14][n2_14];
    W3 = tyi_tab[3][3][n2_3];
    WB_OVERLAP_3();
    WB_OVERLAP_3();
    ab0 = xor_tab[3][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[3][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[3][1][2][0][ab0][cd0];
    WB_OVERLAP_3();
    ab1 = xor_tab[3][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[3][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[3][1][2][1][ab1][cd1];
    WB_OVERLAP_3();
    ab2 = xor_tab[3][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[3][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[3][1][2][2][ab2][cd2];
    WB_OVERLAP_3();
    ab3 = xor_tab[3][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[3][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[3][1][2][3][ab3][cd3];
    WB_OVERLAP_3();
    ab4 = xor_tab[3][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[3][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[3][1][2][4][ab4][cd4];
    WB_OVERLAP_3();
    ab5 = xor_tab[3][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[3][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[3][1][2][5][ab5][cd5];
    WB_OVERLAP_3();
    ab6 = xor_tab[3][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[3][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[3][1][2][6][ab6][cd6];
    WB_OVERLAP_3();
    ab7 = xor_tab[3][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[3][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[3][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n3_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n3_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n3_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n3_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 3, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[3][8][n2_8];
    W1 = tyi_tab[3][13][n2_13];
    W2 = tyi_tab[3][2][n2_2];
    W3 = tyi_tab[3][7][n2_7];
    WB_OVERLAP_3();
    WB_OVERLAP_3();
    ab0 = xor_tab[3][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[3][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[3][2][2][0][ab0][cd0];
    WB_OVERLAP_3();
    ab1 = xor_tab[3][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[3][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[3][2][2][1][ab1][cd1];
    WB_OVERLAP_3();
    ab2 = xor_tab[3][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[3][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[3][2][2][2][ab2][cd2];
    WB_OVERLAP_3();
    ab3 = xor_tab[3][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[3][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[3][2][2][3][ab3][cd3];
    WB_OVERLAP_3();
    ab4 = xor_tab[3][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[3][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[3][2][2][4][ab4][cd4];
    WB_OVERLAP_3();
    ab5 = xor_tab[3][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[3][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[3][2][2][5][ab5][cd5];
    WB_OVERLAP_3();
    ab6 = xor_tab[3][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[3][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[3][2][2][6][ab6][cd6];
    WB_OVERLAP_3();
    ab7 = xor_tab[3][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[3][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[3][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n3_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n3_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n3_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n3_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 3, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[3][12][n2_12];
    W1 = tyi_tab[3][1][n2_1];
    W2 = tyi_tab[3][6][n2_6];
    W3 = tyi_tab[3][11][n2_11];
    WB_OVERLAP_3();
    WB_OVERLAP_3();
    ab0 = xor_tab[3][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[3][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[3][3][2][0][ab0][cd0];
    WB_OVERLAP_3();
    ab1 = xor_tab[3][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[3][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[3][3][2][1][ab1][cd1];
    WB_OVERLAP_3();
    ab2 = xor_tab[3][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[3][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[3][3][2][2][ab2][cd2];
    WB_OVERLAP_3();
    ab3 = xor_tab[3][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[3][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[3][3][2][3][ab3][cd3];
    WB_OVERLAP_3();
    ab4 = xor_tab[3][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[3][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[3][3][2][4][ab4][cd4];
    WB_OVERLAP_3();
    ab5 = xor_tab[3][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[3][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[3][3][2][5][ab5][cd5];
    WB_OVERLAP_3();
    ab6 = xor_tab[3][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[3][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[3][3][2][6][ab6][cd6];
    WB_OVERLAP_3();
    ab7 = xor_tab[3][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[3][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[3][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n3_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n3_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n3_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n3_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 4 ----
    // Round 4, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[4][0][n3_0];
    W1 = tyi_tab[4][5][n3_5];
    W2 = tyi_tab[4][10][n3_10];
    W3 = tyi_tab[4][15][n3_15];
    WB_OVERLAP_4();
    WB_OVERLAP_4();
    ab0 = xor_tab[4][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[4][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[4][0][2][0][ab0][cd0];
    WB_OVERLAP_4();
    ab1 = xor_tab[4][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[4][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[4][0][2][1][ab1][cd1];
    WB_OVERLAP_4();
    ab2 = xor_tab[4][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[4][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[4][0][2][2][ab2][cd2];
    WB_OVERLAP_4();
    ab3 = xor_tab[4][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[4][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[4][0][2][3][ab3][cd3];
    WB_OVERLAP_4();
    ab4 = xor_tab[4][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[4][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[4][0][2][4][ab4][cd4];
    WB_OVERLAP_4();
    ab5 = xor_tab[4][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[4][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[4][0][2][5][ab5][cd5];
    WB_OVERLAP_4();
    ab6 = xor_tab[4][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[4][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[4][0][2][6][ab6][cd6];
    WB_OVERLAP_4();
    ab7 = xor_tab[4][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[4][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[4][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n4_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n4_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n4_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n4_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 4, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[4][4][n3_4];
    W1 = tyi_tab[4][9][n3_9];
    W2 = tyi_tab[4][14][n3_14];
    W3 = tyi_tab[4][3][n3_3];
    WB_OVERLAP_4();
    WB_OVERLAP_4();
    ab0 = xor_tab[4][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[4][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[4][1][2][0][ab0][cd0];
    WB_OVERLAP_4();
    ab1 = xor_tab[4][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[4][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[4][1][2][1][ab1][cd1];
    WB_OVERLAP_4();
    ab2 = xor_tab[4][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[4][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[4][1][2][2][ab2][cd2];
    WB_OVERLAP_4();
    ab3 = xor_tab[4][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[4][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[4][1][2][3][ab3][cd3];
    WB_OVERLAP_4();
    ab4 = xor_tab[4][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[4][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[4][1][2][4][ab4][cd4];
    WB_OVERLAP_4();
    ab5 = xor_tab[4][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[4][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[4][1][2][5][ab5][cd5];
    WB_OVERLAP_4();
    ab6 = xor_tab[4][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[4][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[4][1][2][6][ab6][cd6];
    WB_OVERLAP_4();
    ab7 = xor_tab[4][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[4][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[4][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n4_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n4_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n4_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n4_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 4, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[4][8][n3_8];
    W1 = tyi_tab[4][13][n3_13];
    W2 = tyi_tab[4][2][n3_2];
    W3 = tyi_tab[4][7][n3_7];
    WB_OVERLAP_4();
    WB_OVERLAP_4();
    ab0 = xor_tab[4][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[4][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[4][2][2][0][ab0][cd0];
    WB_OVERLAP_4();
    ab1 = xor_tab[4][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[4][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[4][2][2][1][ab1][cd1];
    WB_OVERLAP_4();
    ab2 = xor_tab[4][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[4][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[4][2][2][2][ab2][cd2];
    WB_OVERLAP_4();
    ab3 = xor_tab[4][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[4][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[4][2][2][3][ab3][cd3];
    WB_OVERLAP_4();
    ab4 = xor_tab[4][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[4][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[4][2][2][4][ab4][cd4];
    WB_OVERLAP_4();
    ab5 = xor_tab[4][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[4][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[4][2][2][5][ab5][cd5];
    WB_OVERLAP_4();
    ab6 = xor_tab[4][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[4][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[4][2][2][6][ab6][cd6];
    WB_OVERLAP_4();
    ab7 = xor_tab[4][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[4][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[4][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n4_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n4_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n4_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n4_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 4, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[4][12][n3_12];
    W1 = tyi_tab[4][1][n3_1];
    W2 = tyi_tab[4][6][n3_6];
    W3 = tyi_tab[4][11][n3_11];
    WB_OVERLAP_4();
    WB_OVERLAP_4();
    ab0 = xor_tab[4][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[4][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[4][3][2][0][ab0][cd0];
    WB_OVERLAP_4();
    ab1 = xor_tab[4][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[4][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[4][3][2][1][ab1][cd1];
    WB_OVERLAP_4();
    ab2 = xor_tab[4][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[4][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[4][3][2][2][ab2][cd2];
    WB_OVERLAP_4();
    ab3 = xor_tab[4][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[4][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[4][3][2][3][ab3][cd3];
    WB_OVERLAP_4();
    ab4 = xor_tab[4][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[4][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[4][3][2][4][ab4][cd4];
    WB_OVERLAP_4();
    ab5 = xor_tab[4][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[4][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[4][3][2][5][ab5][cd5];
    WB_OVERLAP_4();
    ab6 = xor_tab[4][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[4][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[4][3][2][6][ab6][cd6];
    WB_OVERLAP_4();
    ab7 = xor_tab[4][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[4][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[4][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n4_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n4_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n4_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n4_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 5 ----
    // Round 5, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[5][0][n4_0];
    W1 = tyi_tab[5][5][n4_5];
    W2 = tyi_tab[5][10][n4_10];
    W3 = tyi_tab[5][15][n4_15];
    WB_OVERLAP_5();
    WB_OVERLAP_5();
    ab0 = xor_tab[5][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[5][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[5][0][2][0][ab0][cd0];
    WB_OVERLAP_5();
    ab1 = xor_tab[5][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[5][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[5][0][2][1][ab1][cd1];
    WB_OVERLAP_5();
    ab2 = xor_tab[5][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[5][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[5][0][2][2][ab2][cd2];
    WB_OVERLAP_5();
    ab3 = xor_tab[5][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[5][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[5][0][2][3][ab3][cd3];
    WB_OVERLAP_5();
    ab4 = xor_tab[5][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[5][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[5][0][2][4][ab4][cd4];
    WB_OVERLAP_5();
    ab5 = xor_tab[5][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[5][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[5][0][2][5][ab5][cd5];
    WB_OVERLAP_5();
    ab6 = xor_tab[5][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[5][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[5][0][2][6][ab6][cd6];
    WB_OVERLAP_5();
    ab7 = xor_tab[5][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[5][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[5][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n5_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n5_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n5_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n5_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 5, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[5][4][n4_4];
    W1 = tyi_tab[5][9][n4_9];
    W2 = tyi_tab[5][14][n4_14];
    W3 = tyi_tab[5][3][n4_3];
    WB_OVERLAP_5();
    WB_OVERLAP_5();
    ab0 = xor_tab[5][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[5][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[5][1][2][0][ab0][cd0];
    WB_OVERLAP_5();
    ab1 = xor_tab[5][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[5][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[5][1][2][1][ab1][cd1];
    WB_OVERLAP_5();
    ab2 = xor_tab[5][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[5][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[5][1][2][2][ab2][cd2];
    WB_OVERLAP_5();
    ab3 = xor_tab[5][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[5][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[5][1][2][3][ab3][cd3];
    WB_OVERLAP_5();
    ab4 = xor_tab[5][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[5][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[5][1][2][4][ab4][cd4];
    WB_OVERLAP_5();
    ab5 = xor_tab[5][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[5][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[5][1][2][5][ab5][cd5];
    WB_OVERLAP_5();
    ab6 = xor_tab[5][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[5][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[5][1][2][6][ab6][cd6];
    WB_OVERLAP_5();
    ab7 = xor_tab[5][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[5][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[5][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n5_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n5_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n5_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n5_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 5, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[5][8][n4_8];
    W1 = tyi_tab[5][13][n4_13];
    W2 = tyi_tab[5][2][n4_2];
    W3 = tyi_tab[5][7][n4_7];
    WB_OVERLAP_5();
    WB_OVERLAP_5();
    ab0 = xor_tab[5][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[5][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[5][2][2][0][ab0][cd0];
    WB_OVERLAP_5();
    ab1 = xor_tab[5][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[5][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[5][2][2][1][ab1][cd1];
    WB_OVERLAP_5();
    ab2 = xor_tab[5][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[5][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[5][2][2][2][ab2][cd2];
    WB_OVERLAP_5();
    ab3 = xor_tab[5][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[5][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[5][2][2][3][ab3][cd3];
    WB_OVERLAP_5();
    ab4 = xor_tab[5][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[5][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[5][2][2][4][ab4][cd4];
    WB_OVERLAP_5();
    ab5 = xor_tab[5][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[5][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[5][2][2][5][ab5][cd5];
    WB_OVERLAP_5();
    ab6 = xor_tab[5][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[5][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[5][2][2][6][ab6][cd6];
    WB_OVERLAP_5();
    ab7 = xor_tab[5][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[5][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[5][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n5_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n5_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n5_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n5_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 5, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[5][12][n4_12];
    W1 = tyi_tab[5][1][n4_1];
    W2 = tyi_tab[5][6][n4_6];
    W3 = tyi_tab[5][11][n4_11];
    WB_OVERLAP_5();
    WB_OVERLAP_5();
    ab0 = xor_tab[5][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[5][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[5][3][2][0][ab0][cd0];
    WB_OVERLAP_5();
    ab1 = xor_tab[5][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[5][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[5][3][2][1][ab1][cd1];
    WB_OVERLAP_5();
    ab2 = xor_tab[5][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[5][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[5][3][2][2][ab2][cd2];
    WB_OVERLAP_5();
    ab3 = xor_tab[5][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[5][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[5][3][2][3][ab3][cd3];
    WB_OVERLAP_5();
    ab4 = xor_tab[5][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[5][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[5][3][2][4][ab4][cd4];
    WB_OVERLAP_5();
    ab5 = xor_tab[5][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[5][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[5][3][2][5][ab5][cd5];
    WB_OVERLAP_5();
    ab6 = xor_tab[5][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[5][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[5][3][2][6][ab6][cd6];
    WB_OVERLAP_5();
    ab7 = xor_tab[5][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[5][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[5][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n5_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n5_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n5_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n5_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 6 ----
    // Round 6, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[6][0][n5_0];
    W1 = tyi_tab[6][5][n5_5];
    W2 = tyi_tab[6][10][n5_10];
    W3 = tyi_tab[6][15][n5_15];
    WB_OVERLAP_6();
    WB_OVERLAP_6();
    ab0 = xor_tab[6][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[6][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[6][0][2][0][ab0][cd0];
    WB_OVERLAP_6();
    ab1 = xor_tab[6][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[6][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[6][0][2][1][ab1][cd1];
    WB_OVERLAP_6();
    ab2 = xor_tab[6][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[6][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[6][0][2][2][ab2][cd2];
    WB_OVERLAP_6();
    ab3 = xor_tab[6][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[6][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[6][0][2][3][ab3][cd3];
    WB_OVERLAP_6();
    ab4 = xor_tab[6][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[6][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[6][0][2][4][ab4][cd4];
    WB_OVERLAP_6();
    ab5 = xor_tab[6][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[6][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[6][0][2][5][ab5][cd5];
    WB_OVERLAP_6();
    ab6 = xor_tab[6][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[6][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[6][0][2][6][ab6][cd6];
    WB_OVERLAP_6();
    ab7 = xor_tab[6][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[6][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[6][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n6_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n6_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n6_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n6_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 6, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[6][4][n5_4];
    W1 = tyi_tab[6][9][n5_9];
    W2 = tyi_tab[6][14][n5_14];
    W3 = tyi_tab[6][3][n5_3];
    WB_OVERLAP_6();
    WB_OVERLAP_6();
    ab0 = xor_tab[6][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[6][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[6][1][2][0][ab0][cd0];
    WB_OVERLAP_6();
    ab1 = xor_tab[6][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[6][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[6][1][2][1][ab1][cd1];
    WB_OVERLAP_6();
    ab2 = xor_tab[6][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[6][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[6][1][2][2][ab2][cd2];
    WB_OVERLAP_6();
    ab3 = xor_tab[6][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[6][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[6][1][2][3][ab3][cd3];
    WB_OVERLAP_6();
    ab4 = xor_tab[6][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[6][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[6][1][2][4][ab4][cd4];
    WB_OVERLAP_6();
    ab5 = xor_tab[6][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[6][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[6][1][2][5][ab5][cd5];
    WB_OVERLAP_6();
    ab6 = xor_tab[6][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[6][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[6][1][2][6][ab6][cd6];
    WB_OVERLAP_6();
    ab7 = xor_tab[6][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[6][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[6][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n6_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n6_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n6_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n6_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 6, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[6][8][n5_8];
    W1 = tyi_tab[6][13][n5_13];
    W2 = tyi_tab[6][2][n5_2];
    W3 = tyi_tab[6][7][n5_7];
    WB_OVERLAP_6();
    WB_OVERLAP_6();
    ab0 = xor_tab[6][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[6][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[6][2][2][0][ab0][cd0];
    WB_OVERLAP_6();
    ab1 = xor_tab[6][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[6][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[6][2][2][1][ab1][cd1];
    WB_OVERLAP_6();
    ab2 = xor_tab[6][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[6][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[6][2][2][2][ab2][cd2];
    WB_OVERLAP_6();
    ab3 = xor_tab[6][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[6][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[6][2][2][3][ab3][cd3];
    WB_OVERLAP_6();
    ab4 = xor_tab[6][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[6][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[6][2][2][4][ab4][cd4];
    WB_OVERLAP_6();
    ab5 = xor_tab[6][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[6][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[6][2][2][5][ab5][cd5];
    WB_OVERLAP_6();
    ab6 = xor_tab[6][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[6][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[6][2][2][6][ab6][cd6];
    WB_OVERLAP_6();
    ab7 = xor_tab[6][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[6][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[6][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n6_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n6_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n6_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n6_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 6, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[6][12][n5_12];
    W1 = tyi_tab[6][1][n5_1];
    W2 = tyi_tab[6][6][n5_6];
    W3 = tyi_tab[6][11][n5_11];
    WB_OVERLAP_6();
    WB_OVERLAP_6();
    ab0 = xor_tab[6][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[6][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[6][3][2][0][ab0][cd0];
    WB_OVERLAP_6();
    ab1 = xor_tab[6][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[6][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[6][3][2][1][ab1][cd1];
    WB_OVERLAP_6();
    ab2 = xor_tab[6][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[6][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[6][3][2][2][ab2][cd2];
    WB_OVERLAP_6();
    ab3 = xor_tab[6][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[6][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[6][3][2][3][ab3][cd3];
    WB_OVERLAP_6();
    ab4 = xor_tab[6][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[6][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[6][3][2][4][ab4][cd4];
    WB_OVERLAP_6();
    ab5 = xor_tab[6][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[6][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[6][3][2][5][ab5][cd5];
    WB_OVERLAP_6();
    ab6 = xor_tab[6][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[6][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[6][3][2][6][ab6][cd6];
    WB_OVERLAP_6();
    ab7 = xor_tab[6][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[6][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[6][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n6_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n6_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n6_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n6_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 7 ----
    // Round 7, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[7][0][n6_0];
    W1 = tyi_tab[7][5][n6_5];
    W2 = tyi_tab[7][10][n6_10];
    W3 = tyi_tab[7][15][n6_15];
    WB_OVERLAP_7();
    WB_OVERLAP_7();
    ab0 = xor_tab[7][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[7][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[7][0][2][0][ab0][cd0];
    WB_OVERLAP_7();
    ab1 = xor_tab[7][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[7][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[7][0][2][1][ab1][cd1];
    WB_OVERLAP_7();
    ab2 = xor_tab[7][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[7][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[7][0][2][2][ab2][cd2];
    WB_OVERLAP_7();
    ab3 = xor_tab[7][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[7][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[7][0][2][3][ab3][cd3];
    WB_OVERLAP_7();
    ab4 = xor_tab[7][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[7][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[7][0][2][4][ab4][cd4];
    WB_OVERLAP_7();
    ab5 = xor_tab[7][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[7][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[7][0][2][5][ab5][cd5];
    WB_OVERLAP_7();
    ab6 = xor_tab[7][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[7][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[7][0][2][6][ab6][cd6];
    WB_OVERLAP_7();
    ab7 = xor_tab[7][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[7][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[7][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n7_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n7_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n7_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n7_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 7, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[7][4][n6_4];
    W1 = tyi_tab[7][9][n6_9];
    W2 = tyi_tab[7][14][n6_14];
    W3 = tyi_tab[7][3][n6_3];
    WB_OVERLAP_7();
    WB_OVERLAP_7();
    ab0 = xor_tab[7][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[7][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[7][1][2][0][ab0][cd0];
    WB_OVERLAP_7();
    ab1 = xor_tab[7][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[7][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[7][1][2][1][ab1][cd1];
    WB_OVERLAP_7();
    ab2 = xor_tab[7][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[7][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[7][1][2][2][ab2][cd2];
    WB_OVERLAP_7();
    ab3 = xor_tab[7][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[7][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[7][1][2][3][ab3][cd3];
    WB_OVERLAP_7();
    ab4 = xor_tab[7][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[7][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[7][1][2][4][ab4][cd4];
    WB_OVERLAP_7();
    ab5 = xor_tab[7][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[7][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[7][1][2][5][ab5][cd5];
    WB_OVERLAP_7();
    ab6 = xor_tab[7][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[7][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[7][1][2][6][ab6][cd6];
    WB_OVERLAP_7();
    ab7 = xor_tab[7][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[7][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[7][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n7_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n7_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n7_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n7_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 7, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[7][8][n6_8];
    W1 = tyi_tab[7][13][n6_13];
    W2 = tyi_tab[7][2][n6_2];
    W3 = tyi_tab[7][7][n6_7];
    WB_OVERLAP_7();
    WB_OVERLAP_7();
    ab0 = xor_tab[7][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[7][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[7][2][2][0][ab0][cd0];
    WB_OVERLAP_7();
    ab1 = xor_tab[7][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[7][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[7][2][2][1][ab1][cd1];
    WB_OVERLAP_7();
    ab2 = xor_tab[7][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[7][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[7][2][2][2][ab2][cd2];
    WB_OVERLAP_7();
    ab3 = xor_tab[7][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[7][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[7][2][2][3][ab3][cd3];
    WB_OVERLAP_7();
    ab4 = xor_tab[7][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[7][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[7][2][2][4][ab4][cd4];
    WB_OVERLAP_7();
    ab5 = xor_tab[7][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[7][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[7][2][2][5][ab5][cd5];
    WB_OVERLAP_7();
    ab6 = xor_tab[7][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[7][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[7][2][2][6][ab6][cd6];
    WB_OVERLAP_7();
    ab7 = xor_tab[7][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[7][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[7][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n7_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n7_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n7_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n7_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 7, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[7][12][n6_12];
    W1 = tyi_tab[7][1][n6_1];
    W2 = tyi_tab[7][6][n6_6];
    W3 = tyi_tab[7][11][n6_11];
    WB_OVERLAP_7();
    WB_OVERLAP_7();
    ab0 = xor_tab[7][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[7][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[7][3][2][0][ab0][cd0];
    WB_OVERLAP_7();
    ab1 = xor_tab[7][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[7][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[7][3][2][1][ab1][cd1];
    WB_OVERLAP_7();
    ab2 = xor_tab[7][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[7][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[7][3][2][2][ab2][cd2];
    WB_OVERLAP_7();
    ab3 = xor_tab[7][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[7][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[7][3][2][3][ab3][cd3];
    WB_OVERLAP_7();
    ab4 = xor_tab[7][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[7][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[7][3][2][4][ab4][cd4];
    WB_OVERLAP_7();
    ab5 = xor_tab[7][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[7][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[7][3][2][5][ab5][cd5];
    WB_OVERLAP_7();
    ab6 = xor_tab[7][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[7][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[7][3][2][6][ab6][cd6];
    WB_OVERLAP_7();
    ab7 = xor_tab[7][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[7][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[7][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n7_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n7_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n7_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n7_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 8 ----
    // Round 8, column 0: src bytes 0,5,10,15
    W0 = tyi_tab[8][0][n7_0];
    W1 = tyi_tab[8][5][n7_5];
    W2 = tyi_tab[8][10][n7_10];
    W3 = tyi_tab[8][15][n7_15];
    WB_OVERLAP_8();
    WB_OVERLAP_8();
    ab0 = xor_tab[8][0][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[8][0][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[8][0][2][0][ab0][cd0];
    WB_OVERLAP_8();
    ab1 = xor_tab[8][0][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[8][0][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[8][0][2][1][ab1][cd1];
    WB_OVERLAP_8();
    ab2 = xor_tab[8][0][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[8][0][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[8][0][2][2][ab2][cd2];
    WB_OVERLAP_8();
    ab3 = xor_tab[8][0][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[8][0][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[8][0][2][3][ab3][cd3];
    WB_OVERLAP_8();
    ab4 = xor_tab[8][0][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[8][0][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[8][0][2][4][ab4][cd4];
    WB_OVERLAP_8();
    ab5 = xor_tab[8][0][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[8][0][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[8][0][2][5][ab5][cd5];
    WB_OVERLAP_8();
    ab6 = xor_tab[8][0][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[8][0][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[8][0][2][6][ab6][cd6];
    WB_OVERLAP_8();
    ab7 = xor_tab[8][0][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[8][0][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[8][0][2][7][ab7][cd7];
    // next[0]
    uint8_t n8_0 = (uint8_t)((fn0 << 4) | fn1);
    // next[1]
    uint8_t n8_1 = (uint8_t)((fn2 << 4) | fn3);
    // next[2]
    uint8_t n8_2 = (uint8_t)((fn4 << 4) | fn5);
    // next[3]
    uint8_t n8_3 = (uint8_t)((fn6 << 4) | fn7);

    // Round 8, column 1: src bytes 4,9,14,3
    W0 = tyi_tab[8][4][n7_4];
    W1 = tyi_tab[8][9][n7_9];
    W2 = tyi_tab[8][14][n7_14];
    W3 = tyi_tab[8][3][n7_3];
    WB_OVERLAP_8();
    WB_OVERLAP_8();
    ab0 = xor_tab[8][1][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[8][1][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[8][1][2][0][ab0][cd0];
    WB_OVERLAP_8();
    ab1 = xor_tab[8][1][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[8][1][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[8][1][2][1][ab1][cd1];
    WB_OVERLAP_8();
    ab2 = xor_tab[8][1][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[8][1][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[8][1][2][2][ab2][cd2];
    WB_OVERLAP_8();
    ab3 = xor_tab[8][1][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[8][1][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[8][1][2][3][ab3][cd3];
    WB_OVERLAP_8();
    ab4 = xor_tab[8][1][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[8][1][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[8][1][2][4][ab4][cd4];
    WB_OVERLAP_8();
    ab5 = xor_tab[8][1][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[8][1][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[8][1][2][5][ab5][cd5];
    WB_OVERLAP_8();
    ab6 = xor_tab[8][1][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[8][1][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[8][1][2][6][ab6][cd6];
    WB_OVERLAP_8();
    ab7 = xor_tab[8][1][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[8][1][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[8][1][2][7][ab7][cd7];
    // next[4]
    uint8_t n8_4 = (uint8_t)((fn0 << 4) | fn1);
    // next[5]
    uint8_t n8_5 = (uint8_t)((fn2 << 4) | fn3);
    // next[6]
    uint8_t n8_6 = (uint8_t)((fn4 << 4) | fn5);
    // next[7]
    uint8_t n8_7 = (uint8_t)((fn6 << 4) | fn7);

    // Round 8, column 2: src bytes 8,13,2,7
    W0 = tyi_tab[8][8][n7_8];
    W1 = tyi_tab[8][13][n7_13];
    W2 = tyi_tab[8][2][n7_2];
    W3 = tyi_tab[8][7][n7_7];
    WB_OVERLAP_8();
    WB_OVERLAP_8();
    ab0 = xor_tab[8][2][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[8][2][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[8][2][2][0][ab0][cd0];
    WB_OVERLAP_8();
    ab1 = xor_tab[8][2][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[8][2][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[8][2][2][1][ab1][cd1];
    WB_OVERLAP_8();
    ab2 = xor_tab[8][2][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[8][2][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[8][2][2][2][ab2][cd2];
    WB_OVERLAP_8();
    ab3 = xor_tab[8][2][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[8][2][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[8][2][2][3][ab3][cd3];
    WB_OVERLAP_8();
    ab4 = xor_tab[8][2][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[8][2][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[8][2][2][4][ab4][cd4];
    WB_OVERLAP_8();
    ab5 = xor_tab[8][2][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[8][2][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[8][2][2][5][ab5][cd5];
    WB_OVERLAP_8();
    ab6 = xor_tab[8][2][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[8][2][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[8][2][2][6][ab6][cd6];
    WB_OVERLAP_8();
    ab7 = xor_tab[8][2][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[8][2][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[8][2][2][7][ab7][cd7];
    // next[8]
    uint8_t n8_8 = (uint8_t)((fn0 << 4) | fn1);
    // next[9]
    uint8_t n8_9 = (uint8_t)((fn2 << 4) | fn3);
    // next[10]
    uint8_t n8_10 = (uint8_t)((fn4 << 4) | fn5);
    // next[11]
    uint8_t n8_11 = (uint8_t)((fn6 << 4) | fn7);

    // Round 8, column 3: src bytes 12,1,6,11
    W0 = tyi_tab[8][12][n7_12];
    W1 = tyi_tab[8][1][n7_1];
    W2 = tyi_tab[8][6][n7_6];
    W3 = tyi_tab[8][11][n7_11];
    WB_OVERLAP_8();
    WB_OVERLAP_8();
    ab0 = xor_tab[8][3][0][0][(W0 >> 28) & 0xF][(W1 >> 28) & 0xF];
    cd0 = xor_tab[8][3][1][0][(W2 >> 28) & 0xF][(W3 >> 28) & 0xF];
    fn0 = xor_tab[8][3][2][0][ab0][cd0];
    WB_OVERLAP_8();
    ab1 = xor_tab[8][3][0][1][(W0 >> 24) & 0xF][(W1 >> 24) & 0xF];
    cd1 = xor_tab[8][3][1][1][(W2 >> 24) & 0xF][(W3 >> 24) & 0xF];
    fn1 = xor_tab[8][3][2][1][ab1][cd1];
    WB_OVERLAP_8();
    ab2 = xor_tab[8][3][0][2][(W0 >> 20) & 0xF][(W1 >> 20) & 0xF];
    cd2 = xor_tab[8][3][1][2][(W2 >> 20) & 0xF][(W3 >> 20) & 0xF];
    fn2 = xor_tab[8][3][2][2][ab2][cd2];
    WB_OVERLAP_8();
    ab3 = xor_tab[8][3][0][3][(W0 >> 16) & 0xF][(W1 >> 16) & 0xF];
    cd3 = xor_tab[8][3][1][3][(W2 >> 16) & 0xF][(W3 >> 16) & 0xF];
    fn3 = xor_tab[8][3][2][3][ab3][cd3];
    WB_OVERLAP_8();
    ab4 = xor_tab[8][3][0][4][(W0 >> 12) & 0xF][(W1 >> 12) & 0xF];
    cd4 = xor_tab[8][3][1][4][(W2 >> 12) & 0xF][(W3 >> 12) & 0xF];
    fn4 = xor_tab[8][3][2][4][ab4][cd4];
    WB_OVERLAP_8();
    ab5 = xor_tab[8][3][0][5][(W0 >> 8) & 0xF][(W1 >> 8) & 0xF];
    cd5 = xor_tab[8][3][1][5][(W2 >> 8) & 0xF][(W3 >> 8) & 0xF];
    fn5 = xor_tab[8][3][2][5][ab5][cd5];
    WB_OVERLAP_8();
    ab6 = xor_tab[8][3][0][6][(W0 >> 4) & 0xF][(W1 >> 4) & 0xF];
    cd6 = xor_tab[8][3][1][6][(W2 >> 4) & 0xF][(W3 >> 4) & 0xF];
    fn6 = xor_tab[8][3][2][6][ab6][cd6];
    WB_OVERLAP_8();
    ab7 = xor_tab[8][3][0][7][(W0 >> 0) & 0xF][(W1 >> 0) & 0xF];
    cd7 = xor_tab[8][3][1][7][(W2 >> 0) & 0xF][(W3 >> 0) & 0xF];
    fn7 = xor_tab[8][3][2][7][ab7][cd7];
    // next[12]
    uint8_t n8_12 = (uint8_t)((fn0 << 4) | fn1);
    // next[13]
    uint8_t n8_13 = (uint8_t)((fn2 << 4) | fn3);
    // next[14]
    uint8_t n8_14 = (uint8_t)((fn4 << 4) | fn5);
    // next[15]
    uint8_t n8_15 = (uint8_t)((fn6 << 4) | fn7);

    // ---- Round 10 (final T-boxes) ----
    out[0] = t10_tab[0][n8_0];
    out[1] = t10_tab[1][n8_5];
    out[2] = t10_tab[2][n8_10];
    out[3] = t10_tab[3][n8_15];
    out[4] = t10_tab[4][n8_4];
    out[5] = t10_tab[5][n8_9];
    out[6] = t10_tab[6][n8_14];
    out[7] = t10_tab[7][n8_3];
    out[8] = t10_tab[8][n8_8];
    out[9] = t10_tab[9][n8_13];
    out[10] = t10_tab[10][n8_2];
    out[11] = t10_tab[11][n8_7];
    out[12] = t10_tab[12][n8_12];
    out[13] = t10_tab[13][n8_1];
    out[14] = t10_tab[14][n8_6];
    out[15] = t10_tab[15][n8_11];
}

static inline bool wb_validate_key(const char* key_str) {
    uint8_t plain[32] = {};
    for (int i = 0; i < 22 && key_str[i]; ++i)
        plain[i] = (uint8_t)key_str[i];
    uint8_t ct[32];
    wb_aes_encrypt(plain,      ct);
    wb_aes_encrypt(plain + 16, ct + 16);
    uint8_t diff = 0;
    for (int i = 0; i < 32; ++i)
        diff |= (ct[i] ^ expected_ct[i]);
    return diff == 0;
}
