#!/usr/bin/env python3

import sys
import secrets

SR_MAP = [0, 5, 10, 15, 4, 9, 14, 3, 8, 13, 2, 7, 12, 1, 6, 11]


_FILLER_FORBIDDEN = frozenset([
    0x00,
    0xC3,        # RET
    0xCC,        # INT3
    0xCD,        # INT imm8
    0xCE, 0xCF,  # INTO, IRET
    0xE8,        # CALL rel32
    0xE9,        # JMP rel32
    0xEB,        # JMP rel8
    0xEE, 0xEF,  # OUT dx,al / OUT dx,eax
    0x0F,        # two-byte escape (UD2, SYSCALL, …)
    0xFF,        # Group 5 (indirect CALL/JMP/PUSH)
])

def rand_filler_bytes(n: int) -> list[int]:
    result = []
    while len(result) < n:
        b = secrets.randbelow(256)
        if b not in _FILLER_FORBIDDEN:
            result.append(b)
    return result

_MBA_PREDICATES = [
    # r=0: x*(x+1) always even; bit 0 == 0. Gap 9.
    (
        'movl %%esp, %%eax\n\t'
        'leal 1(%%eax), %%ecx\n\t'
        'imull %%ecx, %%eax\n\t'
        'testl $1, %%eax\n\t',
        [0x48, 0xB9], 7, []
    ),
    # r=1: 4x - 2x - 2x == 0. Gap 6.
    # IMUL $4 → ecx=4x; addl eax,eax → eax=2x; 4x-2x-2x=0.
    (
        'movl %%esp, %%eax\n\t'
        'imull $4, %%eax, %%ecx\n\t'
        'addl %%eax, %%eax\n\t'
        'subl %%eax, %%ecx\n\t'
        'subl %%eax, %%ecx\n\t'
        'testl %%ecx, %%ecx\n\t',
        [0x48, 0x81, 0xF0], 3, []  # XOR RAX, imm32
    ),
    # r=2: x*3 XOR (x+x+x) == 0  (distributivity). Gap 4.
    (
        'movl %%esp, %%eax\n\t'
        'imull $3, %%eax, %%ecx\n\t'
        'leal (%%eax,%%eax,2), %%eax\n\t'
        'xorl %%ecx, %%eax\n\t'
        'testl %%eax, %%eax\n\t',
        [0x68], 3, []  # PUSH imm32
    ),
    # r=3: (x ROL 11) ROR 11 XOR x == 0. Gap 9.

    # ROL/ROR by the same count compose to identity; x XOR x = 0.
    (
        'movl %%esp, %%eax\n\t'
        'movl %%eax, %%ecx\n\t'
        'roll $11, %%ecx\n\t'
        'rorl $11, %%ecx\n\t'
        'xorl %%eax, %%ecx\n\t'
        'testl %%ecx, %%ecx\n\t',
        [0x48, 0xBB], 7, []
    ),
    # r=4: (2x - x) - x == 0. Gap 6.
    (
        'movl %%esp, %%eax\n\t'
        'leal (%%eax,%%eax), %%ecx\n\t'
        'subl %%eax, %%ecx\n\t'
        'subl %%eax, %%ecx\n\t'
        'testl %%ecx, %%ecx\n\t',
        [0x48, 0x81, 0xF2], 3, []  # XOR RDX, imm32
    ),
    # r=5: (x+x) XOR (x IMUL 2) == 0. Gap 4.
    (
        'movl %%esp, %%eax\n\t'
        'leal (%%eax,%%eax), %%ecx\n\t'
        'imull $2, %%eax, %%eax\n\t'
        'xorl %%ecx, %%eax\n\t'
        'testl %%eax, %%eax\n\t',
        [0xB8], 3, []  # MOV EAX, imm32
    ),
    # r=6: high 64 bits of zero-extend(esp) * 1 == 0. Gap 9.
    # movl zero-extends ESP into RAX (<2^32); mulq RCX(=1) → RDX:RAX = RAX;
    # product fits in 64 bits → RDX = 0 always.
    (
        'movl %%esp, %%eax\n\t'
        'movl $1, %%ecx\n\t'
        'mulq %%rcx\n\t'
        'testl %%edx, %%edx\n\t',
        [0x48, 0xBD], 7, ['edx']
    ),
    # r=7: ((x XOR y) XOR y) XOR x == 0  (XOR cancellation chain). Gap 6.
    (
        'movl %%esp, %%eax\n\t'
        'movl %%ebp, %%ecx\n\t'
        'xorl %%ecx, %%eax\n\t'
        'xorl %%ecx, %%eax\n\t'
        'xorl %%esp, %%eax\n\t'
        'testl %%eax, %%eax\n\t',
        [0x48, 0x81, 0xF5], 3, []  # XOR RBP, imm32
    ),
    # r=8: MBA combo: (x|y)+(x&y) - IMUL(1,x) - y == 0. Gap 4.
    (
        'movl %%esp, %%eax\n\t'
        'movl %%ebp, %%ecx\n\t'
        'orl  %%ecx, %%eax\n\t'
        'andl %%esp, %%ecx\n\t'
        'addl %%ecx, %%eax\n\t'
        'imull $1, %%esp, %%ecx\n\t'
        'subl %%ecx, %%eax\n\t'
        'subl %%ebp, %%eax\n\t'
        'testl %%eax, %%eax\n\t',
        [0xBA], 3, []  # MOV EDX, imm32
    ),
]

SR_FOR_COL = [
    [ 0,  5, 10, 15],
    [ 4,  9, 14,  3],
    [ 8, 13,  2,  7],
    [12,  1,  6, 11],
]

def emit(lines: list[str], s: str, indent: int = 0):
    lines.append("    " * indent + s)

def generate() -> str:
    L: list[str] = []

    L.append("// AUTO-GENERATED by gen_wb_aes.py -- DO NOT EDIT")
    L.append("#pragma once")
    L.append("#include <cstdint>")
    L.append("#include <cstring>")
    L.append('#include "wb_tables.h"')
    L.append("")

    L.append("#ifdef __x86_64__")
    for r, (pred_asm, dead_header, filler_count, extra_clobbers) in enumerate(_MBA_PREDICATES):
        filler       = rand_filler_bytes(filler_count)
        header_str   = ", ".join(f"0x{b:02x}" for b in dead_header)
        filler_str   = ", ".join(f"0x{b:02x}" for b in filler)
        all_clobbers = ["eax", "ecx", "cc", "memory"] + extra_clobbers
        clobber_str  = ", ".join(f'"{c}"' for c in all_clobbers)
        pred_escaped = pred_asm.replace('\n\t', '\\n\\t').replace('"', '\\"')
        L.append(
            f'#define WB_OVERLAP_{r}() do {{ __asm__ volatile('
            f'"{pred_escaped}"'
            f' "jnz 2f\\n\\t"'
            f' "jmp 1f\\n\\t"'
            f' "2:\\n\\t"'
            f' ".byte {header_str}\\n\\t"'
            f' ".byte {filler_str}\\n\\t"'
            f' "1:\\n\\t"'
            f' ::: {clobber_str}); }} while(0)'
        )
    L.append("#else")
    for r in range(9):
        L.append(f"#define WB_OVERLAP_{r}() do {{}} while(0)")
    L.append("#endif")
    L.append("")

    L.append("static __attribute__((noinline)) void wb_aes_encrypt(const uint8_t in[16], uint8_t out[16]) {")
    L.append("    uint8_t s0, s1, s2, s3, s4, s5, s6, s7,")
    L.append("            s8, s9, s10, s11, s12, s13, s14, s15;")
    L.append("    uint32_t W0, W1, W2, W3;")
    L.append("    uint8_t ab0, ab1, ab2, ab3, ab4, ab5, ab6, ab7;")
    L.append("    uint8_t cd0, cd1, cd2, cd3, cd4, cd5, cd6, cd7;")
    L.append("    uint8_t fn0, fn1, fn2, fn3, fn4, fn5, fn6, fn7;")
    L.append("")

    for i in range(16):
        L.append(f"    s{i} = in[{i}];")
    L.append("")

    state_vars = [f"s{i}" for i in range(16)]

    for r in range(9):
        L.append(f"    // ---- Round {r} ----")
        next_vars = [None] * 16

        for j in range(4):
            b0, b1, b2, b3 = SR_FOR_COL[j]
            v0, v1, v2, v3 = state_vars[b0], state_vars[b1], state_vars[b2], state_vars[b3]

            L.append(f"    // Round {r}, column {j}: src bytes {b0},{b1},{b2},{b3}")
            L.append(f"    W0 = tyi_tab[{r}][{b0}][{v0}];")
            L.append(f"    W1 = tyi_tab[{r}][{b1}][{v1}];")
            L.append(f"    W2 = tyi_tab[{r}][{b2}][{v2}];")
            L.append(f"    W3 = tyi_tab[{r}][{b3}][{v3}];")
            L.append(f"    WB_OVERLAP_{r}();")

            for p in range(8):
                shift = 28 - 4 * p
                L.append(f"    WB_OVERLAP_{r}();")
                L.append(f"    ab{p} = xor_tab[{r}][{j}][0][{p}][(W0 >> {shift}) & 0xF][(W1 >> {shift}) & 0xF];")
                L.append(f"    cd{p} = xor_tab[{r}][{j}][1][{p}][(W2 >> {shift}) & 0xF][(W3 >> {shift}) & 0xF];")
                L.append(f"    fn{p} = xor_tab[{r}][{j}][2][{p}][ab{p}][cd{p}];")

            for k in range(4):
                out_byte = 4 * j + k
                L.append(f"    // next[{out_byte}]")
                next_vars[out_byte] = f"n{r}_{out_byte}"
                L.append(f"    uint8_t n{r}_{out_byte} = (uint8_t)((fn{2*k} << 4) | fn{2*k+1});")

            L.append("")

        for i in range(16):
            state_vars[i] = next_vars[i]

    L.append("    // ---- Round 10 (final T-boxes) ----")
    for i in range(16):
        src = SR_MAP[i]
        L.append(f"    out[{i}] = t10_tab[{i}][{state_vars[src]}];")

    L.append("}")
    L.append("")
    L.append("static inline bool wb_validate_key(const char* key_str) {")
    L.append("    uint8_t plain[32] = {};")
    L.append("    for (int i = 0; i < 22 && key_str[i]; ++i)")
    L.append("        plain[i] = (uint8_t)key_str[i];")
    L.append("    uint8_t ct[32];")
    L.append("    wb_aes_encrypt(plain,      ct);")
    L.append("    wb_aes_encrypt(plain + 16, ct + 16);")
    L.append("    uint8_t diff = 0;")
    L.append("    for (int i = 0; i < 32; ++i)")
    L.append("        diff |= (ct[i] ^ expected_ct[i]);")
    L.append("    return diff == 0;")
    L.append("}")
    L.append("")

    return "\n".join(L)


if __name__ == "__main__":
    out_path = sys.argv[1] if len(sys.argv) > 1 else "../wb_aes.h"
    content = generate()
    with open(out_path, "w") as f:
        f.write(content)
    print(f"[gen_wb_aes] wrote {out_path}")
    overlap_count = 9 * 4 * (1 + 8)  # 1 post-W + 8 pre-nibble per column
    print(f"[gen_wb_aes] {content.count(chr(10))} lines, "
          f"{9*4} column blocks × 8 nibble steps, {overlap_count} overlap sequences")
