[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = { version = "0.10.3" }
packets = { path = "../packets" }
tokio = { version = "1.49.0", features = ["full"] }
sha2 = { version = "0.10.9" }
eyre = { version = "0.6.12" }
rkyv = { version = "0.8.14", features = ["std", "bytecheck"] }
game = { path = "../game" }
